apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-app
  labels:
    app: java-demo-app
spec:
  selector:
    matchLabels:
      app: java-demo-app
  template:
    metadata:
      labels:
        app: java-demo-app
    spec:
      containers:
      - name: java-demo-app
        image: 350235531576.dkr.ecr.us-east-1.amazonaws.com/java-demo-app:d5c02b88fc6fa812280ec428a3dde95097c968a6
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

          
