apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 88.5.2
    helm:
      values: |
        prometheus:
          prometheusSpec:
            replicas: 1
            externalLabels:
              cluster: my-cluster
        kubeProxy:
          enabled: false
        grafana:
          service:
            name: grafana
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /grafana
            pathType: Prefix
          env:
            GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana"
            GF_SERVER_SERVE_FROM_SUB_PATH: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true