apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: java-demo-app
spec:
  provider:
    aws:
      service: SecretsManager
      # role: arn:aws:iam::123456789012:role/external-secrets # We are using POD identity so no need
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets